<?php $paymentMethods = $this->getPayemntMethodTitle(); ?>
<?php $cart = $this->getCart(); ?>
<div class="entry-edit">
    <fieldset>
        <span class="nowrap" style="font-size:10px;">
            <?php foreach ($paymentMethods as $key => $value) : ?>
                <input type="radio" class="payment" <?php if ($cart->getPaymentMethodCode() == $key) { ?> checked <?php } ?> name="paymentMethod" value="<?php echo $key ?>"> <?php echo $value->getTitle(); ?><br>
            <?php endforeach; ?>
        </span>
    </fieldset>
</div>