<?php $order = $this->getOrder();
?>
<fieldset>
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="name"> Name <span class="required">*</span></label></td>
                    <td class="value"><?php echo $order->getCustomerName() ?></td>
                </tr>
                <tr>
                    <td class="label"><label for="email">Email <span class="required">*</span></label></td>
                    <td class="value"><?php echo $order->getCustomerEmail() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</fieldset>