<?php $countries = $this->getCountryOptions(); ?>
<?php $billingAddress = $this->getBillingAddress();
?>
<fieldset>
    <div class="order-address" id="order-billing_address_fields">
        <div class="content">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="name">Name <span class="required">*</span></label></td>
                            <td class="value"> <?php echo $billingAddress->getName() ?> </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="address">Address <span class="required">*</span></label></td>
                            <td class="value"> <?php echo $billingAddress->getAddress() ?> </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="city">City <span class="required">*</span></label></td>
                            <td class="value"><?php echo $billingAddress->getCity() ?> </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="state">State <span class="required">*</span></label></td>
                            <td class="value"> <?php echo $billingAddress->getState() ?> </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="zipcode">Zipcode <span class="required">*</span></label></td>
                            <td class="value"> <?php echo $billingAddress->getZipcode() ?> </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="country_id">Country <span class="required">*</span></label></td>
                            <td class="value"><?php echo $billingAddress->getCountry() ?> </td>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</fieldset>