<?php $customer = $this->getCustomerInfo(); ?>
<fieldset>
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="name"> Name <span class="required">*</span></label></td>
                    <td class="value"><?php echo $customer->getName() ?></td>
                </tr>
                <tr>
                    <td class="label"><label for="email">Email <span class="required">*</span></label></td>
                    <td class="value"><?php echo $customer->getEmail() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</fieldset>