<div class="entry-edit">
    <form method="post" id="billingform" action="<?php echo $this->getUrl('*/adminhtml_order_create/saveBillingAddress', ['_current' => true]); ?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <div style="float: right;">
                <button type="submit" form="billingform"><span>Save</span></button>
            </div>
            <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
        </div>
        <div>
            <?php echo $this->getChild('billingAddressForm')->setCart($this->getCart())->toHtml(); ?>
        </div>
    </form>
</div>