<div class="entry-edit">
    <form id="shippingform" action="<?php echo $this->getUrl('*/adminhtml_order_create/saveShippingAddress', ['_current' => true]); ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <div style="float: right;"><button title="Save" onclick="checkShippingForm()" type="button" class="scalable save"><span><span><span>Save</span></span></span></button></div>
            <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
        </div>
        <div class="fieldset">
            <?php echo $this->getChild('shippingAddressForm', true, true)->setCart($this->getCart())->toHtml(); ?>
        </div>
    </form>
</div>

<script type="text/javascript">
    function disabledFields(box) {
        if (box.checked == true) {
            document.getElementById("shipping_name").disabled = true;
            document.getElementById("shipping_address").disabled = true;
            document.getElementById("shipping_city").disabled = true;
            document.getElementById("shipping_state").disabled = true;
            document.getElementById("shipping_zipcode").disabled = true;
            document.getElementById("shipping_country_id").disabled = true;
        } else {
            document.getElementById("shipping_name").disabled = false;
            document.getElementById("shipping_address").disabled = false;
            document.getElementById("shipping_city").disabled = false;
            document.getElementById("shipping_state").disabled = false;
            document.getElementById("shipping_zipcode").disabled = false;
            document.getElementById("shipping_country_id").disabled = false;
        }
    }
    disabledFields(document.getElementById("save-in-shipping-address-book"));

    function checkShippingForm() {
        flag = 0;
        checkbox = document.getElementById('same_as_billing');
        if (checkbox.checked == false) {
            var fields = document.getElementsByClassName('shipping');
            for (var i = 0; i < fields.length; i++) {
                if (fields[i].value == "" || fields[i].value == undefined) {
                    alert("Please Fill " + fields[i].name + " value");
                    flag = 1;
                    return false;
                }
            }
        }
        if (flag) {
            return false;
        } else {
            var form = document.getElementById('shippingform');
            base.setform(form).load();
        }
    }
</script>