<div class="entry-edit">
    <form method="post" id="cartform" action="<?php echo $this->getUrl('*/adminhtml_order_create/updateCart', ['_current' => true]); ?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <div style="float: right;">
                <!-- <a href="" class="btn btn-primary">Update Cart</a> -->
                <button type="button" onclick="base.setform('#cartform').load()" form="cartform"><span>Update Cart</span></button>
            </div>
            <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
        </div>
        <div>
            <?php echo $this->getChild('orderItemsGrid')->toHtml(); ?>
        </div>
    </form>
</div>